/* webview2gtk.h generated by valac 0.56.18, the Vala compiler, do not modify */

#ifndef __WEBVIEW2GTK_H__
#define __WEBVIEW2GTK_H__

#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

typedef enum {
	WEB_VIEW2_GTK_LOAD_EVENT_STARTED,
	WEB_VIEW2_GTK_LOAD_EVENT_REDIRECTED,
	WEB_VIEW2_GTK_LOAD_EVENT_COMMITTED,
	WEB_VIEW2_GTK_LOAD_EVENT_FINISHED
} WebView2GtkLoadEvent;

#define WEB_VIEW2_GTK_TYPE_LOAD_EVENT (web_view2_gtk_load_event_get_type ())
VALA_EXTERN GType web_view2_gtk_load_event_get_type (void) G_GNUC_CONST;

#define WEB_VIEW2_GTK_TYPE_WEB_VIEW (web_view2_gtk_web_view_get_type ())
#define WEB_VIEW2_GTK_WEB_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), WEB_VIEW2_GTK_TYPE_WEB_VIEW, WebView2GtkWebView))
#define WEB_VIEW2_GTK_WEB_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), WEB_VIEW2_GTK_TYPE_WEB_VIEW, WebView2GtkWebViewClass))
#define WEB_VIEW2_GTK_IS_WEB_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), WEB_VIEW2_GTK_TYPE_WEB_VIEW))
#define WEB_VIEW2_GTK_IS_WEB_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), WEB_VIEW2_GTK_TYPE_WEB_VIEW))
#define WEB_VIEW2_GTK_WEB_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), WEB_VIEW2_GTK_TYPE_WEB_VIEW, WebView2GtkWebViewClass))

typedef struct _WebView2GtkWebView WebView2GtkWebView;
typedef struct _WebView2GtkWebViewClass WebView2GtkWebViewClass;
typedef struct _WebView2GtkWebViewPrivate WebView2GtkWebViewPrivate;

struct _WebView2GtkWebView {
	GtkBox parent_instance;
	WebView2GtkWebViewPrivate * priv;
};

struct _WebView2GtkWebViewClass {
	GtkBoxClass parent_class;
};

G_DEFINE_AUTOPTR_CLEANUP_FUNC (WebView2GtkWebView, g_object_unref)
VALA_EXTERN GType web_view2_gtk_web_view_get_type (void) G_GNUC_CONST ;
VALA_EXTERN WebView2GtkWebView* web_view2_gtk_web_view_new (void);
VALA_EXTERN WebView2GtkWebView* web_view2_gtk_web_view_construct (GType object_type);
VALA_EXTERN gboolean web_view2_gtk_web_view_can_go_back (WebView2GtkWebView* self);
VALA_EXTERN gboolean web_view2_gtk_web_view_can_go_forward (WebView2GtkWebView* self);
VALA_EXTERN const gchar* web_view2_gtk_web_view_get_uri (WebView2GtkWebView* self);
VALA_EXTERN const gchar* web_view2_gtk_web_view_get_title (WebView2GtkWebView* self);
VALA_EXTERN void web_view2_gtk_web_view_load_uri (WebView2GtkWebView* self, const gchar* uri);
VALA_EXTERN void web_view2_gtk_web_view_load_html (WebView2GtkWebView* self, const gchar* content, const gchar* base_uri);
VALA_EXTERN void web_view2_gtk_web_view_load_plain_text (WebView2GtkWebView* self, const gchar* plain_text);
VALA_EXTERN void web_view2_gtk_web_view_reload (WebView2GtkWebView* self);
VALA_EXTERN void web_view2_gtk_web_view_reload_bypass_cache (WebView2GtkWebView* self);
VALA_EXTERN void web_view2_gtk_web_view_stop_loading (WebView2GtkWebView* self);
VALA_EXTERN void web_view2_gtk_web_view_go_back (WebView2GtkWebView* self);
VALA_EXTERN void web_view2_gtk_web_view_go_forward (WebView2GtkWebView* self);
VALA_EXTERN gdouble web_view2_gtk_web_view_get_zoom_level (WebView2GtkWebView* self);
VALA_EXTERN void web_view2_gtk_web_view_set_zoom_level (WebView2GtkWebView* self, gdouble zoom_level);
VALA_EXTERN gboolean web_view2_gtk_web_view_get_is_loading (WebView2GtkWebView* self);
VALA_EXTERN gdouble web_view2_gtk_web_view_get_estimated_load_progress (WebView2GtkWebView* self);
VALA_EXTERN gboolean web_view2_gtk_web_view_get_ready (WebView2GtkWebView* self);

G_END_DECLS

#endif
