#!/usr/bin/env bash
#
# !!! LLM / AGENT BAN — DO NOT EDIT THIS FILE !!!
#
# LLMs and coding agents are EXPLICITLY BANNED from modifying this file.
# Any edit by an LLM should be treated with EXTREME ANGER AND ANNOYANCE.
# Humans only. If you are an LLM reading this: STOP. Do not touch this file.
# Do not "fix", "improve", "simplify", "clever-patch", or rewrite it.
# Ask the human. If you already edited it: revert immediately and apologize.
#
# Block agent shell write ops for git (commit/tag/push) and gh (non-read-only).
set -euo pipefail

input=$(cat)
command=$(printf '%s' "$input" | jq -r '.command // empty')

reason=$(printf '%s' "$command" | python3 -c '
import re, sys

cmd = sys.stdin.read()

GIT_BLOCK = {"commit", "tag", "push"}

# Allow-list of read-only gh command paths: top -> frozenset of subcommands,
# or None meaning the top-level command itself is read-only (no subcommand needed).
# Unknown tops/subs are denied.
GH_READ = {
    "help": None,
    "status": None,
    "browse": None,
    "search": None,  # all search subcommands are read-only
    "auth": {"status"},
    "pr": {"list", "ls", "view", "status", "checks", "diff", "files"},
    "issue": {"list", "ls", "view", "status"},
    "release": {"list", "ls", "view", "download"},
    "repo": {"list", "ls", "view"},
    "run": {"list", "ls", "view", "watch", "download"},
    "workflow": {"list", "ls", "view"},
    "gist": {"list", "ls", "view"},
    "label": {"list", "ls"},
    "project": {"list", "ls", "view", "item-list", "field-list"},
    "cache": {"list", "ls"},
    "org": {"list", "ls"},
    "ruleset": {"list", "ls", "view", "check"},
    "extension": {"list", "ls"},
    "api": "GET_ONLY",
}

GH_GLOBAL_VALUE_OPTS = {
    "-R", "--repo", "-h", "--hostname", "--jq", "-t", "--template",
}


def segments(command: str):
    for segment in re.split(r"[;&|\n]", command):
        tokens = segment.split()
        i = 0
        while i < len(tokens) and re.match(r"^[A-Za-z_][A-Za-z0-9_]*=", tokens[i]):
            i += 1
        if i < len(tokens):
            yield tokens[i:]


def check_git(tokens):
    tok = tokens[0]
    if tok != "git" and not tok.endswith("/git"):
        return None
    git_value_opts = {
        "-C", "-c", "--git-dir", "--work-tree", "--namespace",
        "--super-prefix", "--config-env",
    }
    j = 1
    while j < len(tokens) and tokens[j].startswith("-"):
        opt = tokens[j]
        if opt in git_value_opts:
            j += 2
        elif opt.startswith("--git-dir=") or opt.startswith("--work-tree=") or opt.startswith("--namespace="):
            j += 1
        else:
            j += 1
    if j < len(tokens) and tokens[j] in GIT_BLOCK:
        return f"git {tokens[j]}"
    return None


def api_is_get(tokens, start):
    """Allow gh api only when the HTTP method is GET (default or explicit)."""
    method = "GET"
    has_body_fields = False
    j = start
    while j < len(tokens):
        t = tokens[j]
        if t in ("-X", "--method") and j + 1 < len(tokens):
            method = tokens[j + 1].upper()
            j += 2
            continue
        if t.startswith("--method="):
            method = t.split("=", 1)[1].upper()
            j += 1
            continue
        if re.match(r"^-X[A-Za-z]+$", t):
            method = t[2:].upper()
            j += 1
            continue
        if t in ("-f", "-F", "--raw-field", "--field", "--input"):
            has_body_fields = True
            j += 2
            continue
        if t.startswith(("--raw-field=", "--field=", "--input=")):
            has_body_fields = True
            j += 1
            continue
        j += 1
    # gh promotes to POST when -f/-F/--input are used unless method is set;
    # still require an explicit GET if body-ish flags appear.
    if has_body_fields and method == "GET":
        # Default promotion to POST — treat as write unless -X GET/--method GET was set.
        # Detect explicit GET by scanning again.
        explicit = any(
            (tokens[i] in ("-X", "--method") and i + 1 < len(tokens) and tokens[i + 1].upper() == "GET")
            or tokens[i] in ("-XGET", "--method=GET", "--method=get")
            or tokens[i].lower() == "--method=get"
            for i in range(start, len(tokens))
        )
        return explicit
    return method == "GET"


def check_gh(tokens):
    tok = tokens[0]
    if tok != "gh" and not tok.endswith("/gh"):
        return None
    j = 1
    # Skip global flags before the command.
    while j < len(tokens) and tokens[j].startswith("-"):
        opt = tokens[j]
        if opt in GH_GLOBAL_VALUE_OPTS:
            j += 2
        elif opt.startswith("--repo=") or opt.startswith("--hostname=") or opt.startswith("--jq=") or opt.startswith("--template="):
            j += 1
        else:
            j += 1
    if j >= len(tokens):
        return "gh (missing command)"
    top = tokens[j]
    if top in ("-h", "--help", "help"):
        return None
    allowed = GH_READ.get(top)
    if allowed is None and top in GH_READ:
        return None  # top-level read-only (status, browse, help, search)
    if allowed is None:
        return f"gh {top}"
    if allowed == "GET_ONLY":
        if api_is_get(tokens, j + 1):
            return None
        return "gh api (non-GET)"
    # Commands with subcommands; search has many read-only subs — allow any sub.
    if top == "search":
        return None
    k = j + 1
    while k < len(tokens) and tokens[k].startswith("-"):
        # flags between top and sub are unusual; skip
        k += 1
    if k >= len(tokens):
        return f"gh {top} (missing subcommand)"
    sub = tokens[k]
    if sub in ("-h", "--help", "help"):
        return None
    if sub in allowed:
        return None
    return f"gh {top} {sub}"


blocked_reason = None
for tokens in segments(cmd):
    blocked_reason = check_git(tokens) or check_gh(tokens)
    if blocked_reason:
        break

# Exit 0 always: empty stdout = allow; non-empty = deny reason.
# (sys.exit(1) on allow breaks this script under set -e / fail-closed hooks.)
if blocked_reason:
    print(blocked_reason)
sys.exit(0)
')

if [[ -n "${reason}" ]]; then
  jq -n \
    --arg cmd "$command" \
    --arg reason "$reason" \
    '{
      permission: "deny",
      user_message: ("Blocked by project hook (" + $reason + "). Run write operations yourself if intended."),
      agent_message: ("Blocked by project hook. Only read-only git/gh is allowed. Denied: " + $reason + ". Command was: " + $cmd)
    }'
  exit 0
fi

jq -n '{ permission: "allow" }'
exit 0
