/* Generated by scripts/regen-webview2-host-header.sh — do not edit.
 * Cross-unit include for Vala sources that use Win32.Ui.WebView from src/win32-ui-webview2-host.vala.
 * Keep minimal: each .c unit emits its own symbol declarations and WideString layout. */

#ifndef VALA_WIN32_UI_WEBVIEW2_HOST_H
#define VALA_WIN32_UI_WEBVIEW2_HOST_H

#include <stdbool.h>
#include <stdint.h>
#include <win32-ui-webview2-sdk.h>

#endif
